# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3db6343d011be7b07d8b9f84ac94d2ab96c5394578c3d5c30c4104ffe08621719ac3c31d27a4ad45deab6c4bc04709cf746f86750b8fe2eda7b00c16c72fb613

test:
  secret_key_base: 9e05bc042479e46ef09f886d56dee64562e6724ea42b2a16c4d5b8ede489a939f0da885135755074beea5867408a8c42bf5670f0254c605bea379dfa6703e6af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
